INSERT INTO TBL_STUDENT( PHONE, CURSO, EMAIL, ADDRESS, NAME) VALUES ( 1123452, 'ADS', 'ANA@GMAIL.COM', 'RUA URANO', 'ANA') ;
INSERT INTO TBL_STUDENT( PHONE, CURSO, EMAIL, ADDRESS, NAME) VALUES ( 1212345, 'ADS', 'JULIA@GMAIL.COM', 'JD AEROPORTO', 'JULIA') ;
INSERT INTO TBL_STUDENT( PHONE, CURSO, EMAIL, ADDRESS, NAME) VALUES ( 1212345, 'ADS', 'JOAO@GMAIL.COM', 'JD ', 'JOAO') ;
