INSERT INTO TBL_STUDENT( TELEFONE, COURSE, EMAIL, ENDERECO, NAME) VALUES ( 1123452, 'ADS', 'ANA@GMAIL.COM', 'RUA URANO', 'ANA') ;
INSERT INTO TBL_STUDENT( TELEFONE, COURSE, EMAIL, ENDERECO, NAME) VALUES ( 1212345, 'ADS', 'JULIA@GMAIL.COM', 'JD AEROPORTO', 'JULIA') ;
