INSERT INTO TBL_STUDENT( TELEFONE, CURSO, EMAIL, ENDERECO, NAMES) VALUES ( 1123452, 'ADS', 'ANA@GMAIL.COM', 'RUA URANO', 'ANA') ;
INSERT INTO TBL_STUDENT( TELEFONE, CURSO, EMAIL, ENDERECO, NAMES) VALUES ( 1212345, 'ADS', 'JULIA@GMAIL.COM', 'JD AEROPORTO', 'JULIA') ;
INSERT INTO TBL_STUDENT( TELEFONE, CURSO, EMAIL, ENDERECO, NAMES) VALUES ( 1212345, 'ADS', 'JOAO@GMAIL.COM', 'JD ', 'JOAO') ;
